package abc;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yoshi' at '2/1/17 12:11 AM' with Gradle 2.14.1
 *
 * @author yoshi, @date 2/1/17 12:11 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
